// Package assets embeds static, top-level assets shipped with the app -- at
// present, just the tray/window icon.
//
// Go's //go:embed directive may not use ".." to reach outside the directory
// of the source file that declares it (nor may it follow a symlink), so the
// embed must live next to the asset it embeds rather than in the internal/ui
// package that consumes it. internal/ui imports IconPNG instead. See
// assets/fonts/fonts.go for the same pattern applied to the vendored font.
package assets

import _ "embed"

// IconPNG is the tray and window icon, generated by tools/genicon: a plain
// full-colour PNG. It must never be wrapped in a theme.ThemedResource --
// ThemedResource routes to SetTemplateIcon, a macOS-only path that renders as
// an empty icon on Linux.
//
//go:embed icon.png
var IconPNG []byte
